spring:
  application:
    name: foodiesapi

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PWT}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


#aws configuration
aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  region: ap-south-1
  bucket-name: foodies12


jwt:
  secret:
    key: q2NpY29sZSBzdGFja2V4Y2hhbmdlIGluGVybmF0aW9uYWxpemF0aW9uIHJvYm90cyBpbg==

