spring:
  application:
    name: foodiesapi

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PWT}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

#aws configuration
aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  region: ap-south-1

